const fs = require("fs");
const assert = require("assert");

const screens = fs.readFileSync("frontend/app/screens.js", "utf8");

for (const fn of [
  "renderAdminUsers",
  "renderAdminRoleCatalog",
  "renderAdminPermissionMatrix",
  "renderAdminFieldMasking",
  "renderAdminDataScope",
  "renderAdminRolesWorkbench",
  "renderAdminMenuManagement",
  "renderAdminFunctionCatalog",
  "renderAdminMenusWorkbench",
  "renderAdminCustomerList",
  "renderAdminBusinessYearMaster",
  "renderAdminTaxAgentContracts",
  "renderAdminCustomersWorkbench",
  "renderAdminCustomerAssignment",
  "renderAdminCustomerGroups",
  "renderAdminCustomerRules",
  "renderAdminCustomerDelegation",
  "renderAdminCustomerOverrides",
  "renderAdminCustomerAccessWorkbench",
  "renderAdminLawMaster",
  "renderAdminTaxRates",
  "renderAdminLawLimits",
  "renderAdminLawCredits",
  "renderAdminLawDepreciationLives",
  "renderAdminLawSmeCriteria",
  "renderAdminLawLossRules",
  "renderAdminLawSnapshots",
  "renderAdminLawImpact",
  "renderAdminLawHistory",
  "renderAdminLawWorkbench",
  "renderAdminFormMaster",
  "renderAdminFormVersions",
  "renderAdminFormFields",
  "renderAdminFormValidations",
  "renderAdminFormLinkageRules",
  "renderAdminFormMigration",
  "renderAdminFormEfileMap",
  "renderAdminFormBySet",
  "renderAdminFormImpact",
  "renderAdminFormsWorkbench",
  "renderAdminAuditEvents",
  "renderAdminLoginHistory",
  "renderAdminPermissionChangeHistory",
  "renderAdminSystemSettingsAudit",
  "renderAdminAuditWorkbench",
]) {
  assert(screens.includes(`async function ${fn}(env)`), `${fn} must exist`);
}

for (const needle of [
  'data-admin-stage="security-users"',
  'data-admin-stage="security-roles"',
  'data-admin-stage="security-matrix"',
  'data-admin-stage="security-mask"',
  'data-admin-stage="security-scope"',
  'data-admin-stage="menu-management"',
  'data-admin-stage="function-catalog"',
  'data-admin-stage="customer-list"',
  'data-admin-stage="business-year-master"',
  'data-admin-stage="tax-agent-contracts"',
  'data-admin-stage="customer-access-assign"',
  'data-admin-stage="customer-access-groups"',
  'data-admin-stage="customer-access-rules"',
  'data-admin-stage="customer-access-delegate"',
  'data-admin-stage="customer-access-override"',
  'data-admin-stage="law-master"',
  'data-admin-stage="law-rates"',
  'stage: "law-limits"',
  'stage: "law-credits"',
  'stage: "law-depr-lives"',
  'stage: "law-sme"',
  'stage: "law-loss-rule"',
  'data-admin-stage="law-snapshots"',
  'data-admin-stage="law-impact"',
  'data-admin-stage="law-history"',
  'data-admin-stage="form-master"',
  'data-admin-stage="form-versions"',
  'data-admin-stage="form-fields"',
  'data-admin-stage="form-validations"',
  'data-admin-stage="form-linkage-rule"',
  'data-admin-stage="form-migration"',
  'data-admin-stage="form-efile-map"',
  'data-admin-stage="form-by-set"',
  'data-admin-stage="form-impact"',
  'data-admin-stage="audit-events"',
  'data-admin-stage="audit-login"',
  'data-admin-stage="audit-permission"',
  'data-admin-stage="audit-settings"',
  "Security and permission controls",
  "User management",
  "Role master",
  "Permission matrix",
  "Field masking policy",
  "Data scope policy",
  "Menu and function governance",
  "Menu management",
  "Function code management",
  "Customer master administration",
  "Customer registry",
  "Business-year master",
  "Tax agent contracts",
  "Customer access controls",
  "Customer assignment",
  "Access groups",
  "Access rules",
  "Delegation",
  "Access override",
  "Law and rate version control",
  "Law version master",
  "Corporate tax rates",
  "Limit/rate table",
  "Tax credit/reduction rates",
  "Depreciation lives",
  "SME criteria",
  "Loss carryforward rules",
  "Business-year law snapshots",
  "Impact simulation",
  "Amendment history",
  "Form version administration",
  "Form master",
  "Form versions",
  "Field definitions",
  "Validation rules",
  "Linkage rules",
  "Form migration",
  "E-filing map",
  "Business-year form sets",
  "Audit and change review",
  "Audit events",
  "Login history",
  "Permission change history",
  "System settings audit",
  'request("/api/admin/field-masking")',
  'request("/api/admin/data-scope")',
  'request("/api/login-history")',
  'request("/api/system-settings")',
  'request("/api/permission-change-history")',
  'request("/api/admin/roles")',
  'request("/api/admin/functions")',
  'request("/api/admin/function-codes")',
  'request("/api/admin/menu-functions")',
  'request("/api/admin/role-menu-functions")',
  'request(`/api/admin/menus/${encodeURIComponent(menuKey)}/functions`',
  'request(`${root}/customers`)',
  'request(`${root}/customers`,',
  'request(`${root}/business-years`)',
  'request(`${root}/business-years`,',
  'request(`${root}/tax-agents`)',
  'request(`${root}/tax-agents`,',
  'request("/api/admin/customer-groups")',
  'request("/api/admin/customer-groups",',
  'request("/api/admin/customer-rules")',
  'request("/api/admin/customer-rules",',
  'request("/api/admin/customer-access/override")',
  'request("/api/admin/customer-access/override",',
  'request("/api/law-versioning/impact"',
  'request("/api/tax-rates",',
  'request("/api/tax-limits",',
  'request("/api/law-amendments",',
  'request("/api/form-versioning/efile-map")',
  'request("/api/form-versioning/by-set")',
  'request("/api/form-versioning/impact")',
  'request("/api/form-versioning/forms",',
  'request("/api/form-versioning/versions",',
  'request("/api/form-versioning/relationships",',
  'request("/api/form-versioning/field-references")',
  'request(`/api/form-versioning/versions/${selectedVersion.form_version_id}/fields`',
  'request(`/api/form-versioning/versions/${selectedVersion.form_version_id}/validations`',
  'request(`/api/form-versioning/migrations/${mode}`',
  "renderAdminRouteButtons(activeLeaf, ADMIN_SECURITY_ROUTES, env.locale)",
  "renderAdminRouteButtons(activeLeaf, ADMIN_CUSTOMER_ROUTES, env.locale)",
  "renderAdminRouteButtons(activeLeaf, ADMIN_CUSTOMER_ACCESS_ROUTES, env.locale)",
  "renderAdminRouteButtons(activeLeaf, ADMIN_LAW_ROUTES, env.locale)",
  "renderAdminRouteButtons(activeLeaf, ADMIN_FORM_ROUTES, env.locale)",
  "renderAdminRouteButtons(activeLeaf, ADMIN_AUDIT_ROUTES, env.locale)",
]) {
  assert(screens.includes(needle), `${needle} must be present in the admin workbench implementation`);
}

for (const mapping of [
  ['"admin/cust:list": (env) => renderAdminCustomerList(env)', 'data-admin-stage="customer-list"'],
  ['"admin/cust:by-master": (env) => renderAdminBusinessYearMaster(env)', 'data-admin-stage="business-year-master"'],
  ['"admin/cust:agent": (env) => renderAdminTaxAgentContracts(env)', 'data-admin-stage="tax-agent-contracts"'],
  ['"admin/sec:users": (env) => renderAdminUsers(env)', 'data-admin-stage="security-users"'],
  ['"admin/sec:roles": (env) => renderAdminRoleCatalog(env)', 'data-admin-stage="security-roles"'],
  ['"admin/sec:matrix": (env) => renderAdminPermissionMatrix(env)', 'data-admin-stage="security-matrix"'],
  ['"admin/sec:menus": (env) => renderAdminMenuManagement(env)', 'data-admin-stage="menu-management"'],
  ['"admin/sec:functions": (env) => renderAdminFunctionCatalog(env)', 'data-admin-stage="function-catalog"'],
  ['"admin/sec:mask": (env) => renderAdminFieldMasking(env)', 'data-admin-stage="security-mask"'],
  ['"admin/sec:scope": (env) => renderAdminDataScope(env)', 'data-admin-stage="security-scope"'],
  ['"admin/cacc:assign": (env) => renderAdminCustomerAssignment(env)', 'data-admin-stage="customer-access-assign"'],
  ['"admin/cacc:groups": (env) => renderAdminCustomerGroups(env)', 'data-admin-stage="customer-access-groups"'],
  ['"admin/cacc:rules": (env) => renderAdminCustomerRules(env)', 'data-admin-stage="customer-access-rules"'],
  ['"admin/cacc:delegate": (env) => renderAdminCustomerDelegation(env)', 'data-admin-stage="customer-access-delegate"'],
  ['"admin/cacc:override": (env) => renderAdminCustomerOverrides(env)', 'data-admin-stage="customer-access-override"'],
  ['"admin/law:master": (env) => renderAdminLawMaster(env)', 'data-admin-stage="law-master"'],
  ['"admin/law:rates": (env) => renderAdminTaxRates(env)', 'data-admin-stage="law-rates"'],
  ['"admin/law:limits": (env) => renderAdminLawLimits(env)', 'stage: "law-limits"'],
  ['"admin/law:credits": (env) => renderAdminLawCredits(env)', 'stage: "law-credits"'],
  ['"admin/law:depr-lives": (env) => renderAdminLawDepreciationLives(env)', 'stage: "law-depr-lives"'],
  ['"admin/law:sme": (env) => renderAdminLawSmeCriteria(env)', 'stage: "law-sme"'],
  ['"admin/law:loss-rule": (env) => renderAdminLawLossRules(env)', 'stage: "law-loss-rule"'],
  ['"admin/law:snapshots": (env) => renderAdminLawSnapshots(env)', 'data-admin-stage="law-snapshots"'],
  ['"admin/law:impact": (env) => renderAdminLawImpact(env)', 'data-admin-stage="law-impact"'],
  ['"admin/law:history": (env) => renderAdminLawHistory(env)', 'data-admin-stage="law-history"'],
  ['"admin/form:master": (env) => renderAdminFormMaster(env)', 'data-admin-stage="form-master"'],
  ['"admin/form:versions": (env) => renderAdminFormVersions(env)', 'data-admin-stage="form-versions"'],
  ['"admin/form:fields": (env) => renderAdminFormFields(env)', 'data-admin-stage="form-fields"'],
  ['"admin/form:validations": (env) => renderAdminFormValidations(env)', 'data-admin-stage="form-validations"'],
  ['"admin/form:linkage-rule": (env) => renderAdminFormLinkageRules(env)', 'data-admin-stage="form-linkage-rule"'],
  ['"admin/form:migration": (env) => renderAdminFormMigration(env)', 'data-admin-stage="form-migration"'],
  ['"admin/form:efile-map": (env) => renderAdminFormEfileMap(env)', 'data-admin-stage="form-efile-map"'],
  ['"admin/form:by-set": (env) => renderAdminFormBySet(env)', 'data-admin-stage="form-by-set"'],
  ['"admin/form:impact": (env) => renderAdminFormImpact(env)', 'data-admin-stage="form-impact"'],
  ['"admin/audit:events": (env) => renderAdminAuditEvents(env)', 'data-admin-stage="audit-events"'],
  ['"admin/audit:login": (env) => renderAdminLoginHistory(env)', 'data-admin-stage="audit-login"'],
  ['"admin/audit:perm": (env) => renderAdminPermissionChangeHistory(env)', 'data-admin-stage="audit-permission"'],
  ['"admin/audit:settings": (env) => renderAdminSystemSettingsAudit(env)', 'data-admin-stage="audit-settings"'],
]) {
  assert(screens.includes(mapping[0]), `${mapping[0]} must dispatch to a dedicated admin screen`);
  assert(screens.includes(mapping[1]), `${mapping[1]} must identify the dedicated admin screen`);
}

for (const wrapper of [
  ["renderAdminCustomers", "renderAdminCustomersWorkbench(env)"],
  ["renderAdminRoles", "renderAdminRolesWorkbench(env)"],
  ["renderAdminMenus", "renderAdminMenusWorkbench(env)"],
  ["renderAdminCustomerAccess", "renderAdminCustomerAccessWorkbench(env)"],
  ["renderAdminLaw", "renderAdminLawWorkbench(env)"],
  ["renderAdminForms", "renderAdminFormsWorkbench(env)"],
  ["renderAdminAudit", "renderAdminAuditWorkbench(env)"],
]) {
  const [name, call] = wrapper;
  const start = screens.indexOf(`async function ${name}(env) {`);
  assert(start >= 0, `${name} wrapper must exist`);
  const body = screens.slice(start, start + 220);
  assert(body.includes(`return ${call};`), `${name} must delegate to ${call}`);
}

console.log("frontend admin_settings_workbench.spec.js passed");
