const fs = require("fs");
const assert = require("assert");

const screens = fs.readFileSync("frontend/app/screens.js", "utf8");

for (const snippet of [
  "const validationRunState = new Map();",
  'data-stage="forms"',
  'data-form-stage="form3"',
  'data-form-stage="attachments"',
  'data-form-stage="preview"',
  'data-form-stage="linkage"',
  'data-leaf-key="ws/form:form3"',
  'data-leaf-key="ws/form:attachments"',
  'data-leaf-key="ws/form:preview"',
  'data-leaf-key="ws/form:linkage"',
  'data-stage="validation"',
  'data-validation-stage="run"',
  'data-validation-stage="issues"',
  'data-validation-stage="rules"',
  'data-leaf-key="ws/val:run"',
  'data-leaf-key="ws/val:issues"',
  'data-leaf-key="ws/val:rules"',
  'data-stage="approval"',
  'data-approval-stage="request"',
  'data-approval-stage="inbox"',
  'data-approval-stage="rejected"',
  'data-leaf-key="ws/appr:request"',
  'data-leaf-key="ws/appr:inbox"',
  'data-leaf-key="ws/appr:rejected"',
  'data-stage="print"',
  'data-print-stage="preview"',
  'data-print-stage="bulk"',
  'data-print-stage="history"',
  'data-leaf-key="ws/print:preview"',
  'data-leaf-key="ws/print:bulk"',
  'data-leaf-key="ws/print:history"',
  'data-stage="efiling"',
  'data-efile-stage="precheck"',
  'data-efile-stage="generate"',
  'data-efile-stage="submit"',
  'data-efile-stage="done"',
  'data-leaf-key="ws/file:precheck"',
  'data-leaf-key="ws/file:generate"',
  'data-leaf-key="ws/file:submit"',
  'data-leaf-key="ws/file:done"',
  'data-stage="post-history"',
  'data-stage="post-amend"',
  'data-amend-stage="unlock"',
  'data-amend-stage="version"',
  'data-amend-stage="diff"',
  'data-amend-stage="resubmit"',
  'data-amend-stage="correction"',
  'data-leaf-key="post/amend:unlock"',
  'data-leaf-key="post/amend:version"',
  'data-leaf-key="post/amend:diff"',
  'data-leaf-key="post/amend:resubmit"',
  'data-leaf-key="post/correction"',
  "renderStageRouteButtons(activeLeaf, POST_AMEND_ROUTES, env.locale)",
  'data-form-code="${escapeHtml(data.selectedFormCode)}"',
  'data-form-pdf="${escapeHtml(data.selectedFormCode)}"',
  'data-form-edit-field="${escapeHtml(field.field_path)}"',
  'data-validation-jump="${escapeHtml(validationIssueLeaf(issue))}"',
  'data-dismiss-issue="${escapeHtml(issue.issue_id)}"',
  'data-download-form="${escapeHtml(item.form_code)}"',
  'data-efile-jump="${escapeHtml(efilingIssueLeaf(issue))}"',
  'data-download-efile="${item.efiling_id}"',
  'data-open-amend="${escapeHtml(by.by_id)}"',
  'request(`${root}/forms/linkage-check`)',
  'request(`${root}/forms/${selectedFormCode}/preview`)',
  'request(`${root}/validation/issues`)',
  'request(`${data.root}/workflow/request`',
  'request(`${root}/forms/print-history`)',
  'request(`${root}/efilings/latest`)',
  'request(`${root}/efilings/${latestHistory.efiling_id}/submit`',
  'request(`${root}/amendment-version-mode`)',
  'request(`${data.root}/unlock`',
  'request(`${data.root}/resubmit`',
  'request(`${root}/correction-claims`',
  'downloadBinary(`${root}/forms/pdf-bundle/download`, "forms.zip")',
  'downloadBinary(`${routeRoot(env)}/efilings/${button.dataset.downloadEfile}/file`',
  'env.navigate("ws/appr:request")',
  'env.navigate("post/amend:unlock")',
  'env.navigate("ws/val:run")',
]) {
  assert(screens.includes(snippet), `Phase 5~8 workbench must include ${snippet}`);
}

for (const fn of [
  "statusIn",
  "renderStageRouteButtons",
  "formatWorkbenchValue",
  "parseManualFieldValue",
  "formSourceLeaf",
  "loadFormsWorkbenchData",
  "renderFormsMetrics",
  "renderFormsHeader",
  "renderFormCatalogTable",
  "renderFormPreviewTable",
  "renderFormValidations",
  "renderFormLinkageTable",
  "renderFormOverridePanel",
  "bindFormsRouteButtons",
  "bindFormsCommonActions",
  "validationIssueLeaf",
  "efilingIssueLeaf",
  "validationCounts",
  "loadValidationWorkbenchData",
  "renderValidationHeader",
  "renderValidationGateSummary",
  "bindValidationRouteButtons",
  "loadApprovalWorkbenchData",
  "renderApprovalHeader",
  "approvalLineApprovers",
  "renderApprovalLines",
  "renderWorkflowEvents",
  "bindApprovalRouteButtons",
  "updateWorkflowStatus",
  "loadPrintWorkbenchData",
  "renderPrintHeader",
  "renderPrintMetrics",
  "renderPrintableFormsTable",
  "renderPrintHistoryTable",
  "bindPrintRouteButtons",
  "bindPrintDownloads",
  "loadEfilingWorkbenchData",
  "renderEfilingMetrics",
  "renderEfilingHeader",
  "renderEfilingPrecheckIssues",
  "renderEfilingLatestTable",
  "renderEfilingHistoryTable",
  "bindEfilingRouteButtons",
  "bindEfilingDownloads",
  "bindEfilingCreate",
  "bindEfilingSubmit",
  "loadPostAmendWorkbenchData",
  "renderPostAmendMetrics",
  "renderPostAmendHeader",
  "renderPostAmendDifferenceTable",
  "renderPostAmendVersionTable",
  "renderPostAmendVersionSelect",
  "bindPostAmendRouteButtons",
  "bindPostAmendUnlock",
  "bindPostAmendResubmit",
]) {
  assert(screens.includes(`function ${fn}`), `${fn} helper must exist`);
}

for (const fn of [
  "renderFormsForm3",
  "renderFormsAttachments",
  "renderFormsPreview",
  "renderFormsLinkage",
  "renderValidationRun",
  "renderValidationIssues",
  "renderValidationRules",
  "renderApprovalRequest",
  "renderApprovalInbox",
  "renderApprovalRejected",
  "renderPrintPreview",
  "renderPrintBulk",
  "renderPrintHistory",
  "renderEfilingPrecheck",
  "renderEfilingGenerate",
  "renderEfilingSubmit",
  "renderEfilingDone",
  "renderPostAmendUnlock",
  "renderPostAmendVersion",
  "renderPostAmendDiff",
  "renderPostAmendResubmit",
  "renderPostCorrection",
]) {
  assert(screens.includes(`async function ${fn}(env)`), `${fn} screen must exist`);
}

console.log("frontend phase5_8_workbench.spec.js passed");
